blog/urls.py
# coding: utf-8

from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse, resolve
from views import post_list, post_item, blogger_page


urlpatterns = patterns('',
    url(r'^$', post_list, name='post_list'),
    url(r'post/(?P<slug>[-\w]*)/$', post_item, name='post_item'),
    url(r'blogger/(?P<username>[\w]*)/$', blogger_page, name='blogger_name'),
)

pages/urls.py
# coding: utf-8

from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse, resolve
from views import pages_category, pages_page


urlpatterns = patterns('',
    # url(r'^$', post_list, name='post_list'),
    url(r'category/(?P<slug>[-\w]*)/$', pages_category, name='category'),
    url(r'page/(?P<slug>[-\w]*)/$', pages_page, name='page'),
)

tdukr/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns('',
    url(r'^$', 'core.views.home', name='home'),
    url(r'^about/$', 'core.views.about', name='about'),
    url(r'^about/join-as/$', 'core.views.join_as', name='join_as'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^pages/', include('pages.urls', namespace='pages')),
    url(r'^news/', include('news.urls', namespace='news')),


)

urlpatterns += patterns('',
    url(r'^decent/', 'decent.views.index', name='decent_index'),
)


if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

templates/pages/pages_item.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block content %}
  <header class="sb-page-header">
    <div class="container">
      <h1>{{ page.category.title }}</h1>
      <p>{{ page.title }}</p>
    </div>
  </header>

  <div class="container">
    <ol class="breadcrumb">
      <li><a href="/{{ request.LANGUAGE_CODE }}/">{% trans 'Головна' %}</a></li>
      <li><a href="{% url 'pages:category' page.category.slug %}">{{ page.category.title }}</a></li>
      <li class="active">{{ page.title }}</li>
    </ol>

    <div class="post text">
      <h2>{{ page.title }}</h2>
      <p class="date">{{ page.publish_date|date:'d.m.Y' }}</p>
      {{ page.body|safe }}
    </div>
  </div>

{% endblock %}

templates/pages/pages_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Blogs' %}
{% endblock %}

{% block content %}

  <header class="sb-page-header">
    <div class="container">
      <h1>{{ category.title }}</h1>
      <p>
      </p>
    </div>
  </header>

  <div class="container">
    <ol class="breadcrumb">
      <li><a href="/{{ request.LANGUAGE_CODE }}/">{% trans 'Головна' %}</a></li>
      <li class="active">{{ category.title }}</li>
    </ol>
  </div>

  <div id="posts">

    <div class="container">
      <div class="row">
        <div class="col-md-12">
        {% for c in category.get_children %}
          <div class="post text">
            <h2><a href="{% url 'pages:category' c.slug %}">{{ c.title }}</a></h2>
          </div>
        {% endfor %}


          {% for page in pages %}
{#          <div class="row">#}
{##}
{#            <div class="col-md-4" style="padding-top: 20px;">#}
{#              <p>{% trans 'Опубліковано' %}: {{ post.publish_date|date:'d.m.Y' }}</p>#}
{#              <p>{% trans 'Автор' %}: <a href="{% url 'blog:blogger_name' post.author.username %}">{{ post.author.full_name }}</a></p>#}
{#            </div>#}

{#            <div class="col-md-8">#}
              <div class="post text">
                <h2><a href="{% url 'pages:page' page.slug %}">{{ page.title }}</a></h2>
                {{ page.short_body|safe }}
              </div>
{#            </div>#}

{#          </div>#}
          {% endfor %}

        </div>
      </div>
    </div>

  </div>

{% endblock %}