blog/urls.py
# coding: utf-8

from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse, resolve
from views import post_list, post_item, blogger_page


urlpatterns = patterns('',
    url(r'^$', post_list, name='post_list'),
    url(r'post/(?P<slug>[-\w]*)/$', post_item, name='post_item'),
    url(r'blogger/(?P<username>[\w]*)/$', blogger_page, name='blogger_name'),
)

news/urls.py
# coding: utf-8

from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse, resolve

from views import news_list, news_article


urlpatterns = patterns('',
    url(r'^$', news_list, name='news_list'),
    url(r'(?P<slug>[-\w]*)/$', news_article, name='news_article'),
)

pages/urls.py
# coding: utf-8

from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse, resolve
from views import pages_category, pages_page


urlpatterns = patterns('',
    # url(r'^$', post_list, name='post_list'),
    url(r'category/(?P<slug>[-\w]*)/$', pages_category, name='category'),
    url(r'page/(?P<slug>[-\w]*)/$', pages_page, name='page'),
)

tdukr/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns('',
    url(r'^$', 'core.views.home', name='home'),
    url(r'^about/$', 'core.views.about', name='about'),
    url(r'^about/join-as/$', 'core.views.join_as', name='join_as'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^pages/', include('pages.urls', namespace='pages')),
    url(r'^news/', include('news.urls', namespace='news')),


)

urlpatterns += patterns('',
    url(r'^decent/', 'decent.views.index', name='decent_index'),
)


if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

templates/includes/botton.html
{% load staticfiles %}

<div class="copyright_info">
  <div class="container">
    <div class="one_half"> Copyright © 2014 BrainBasket Foundation. All rights reserved.</div>
  </div>
</div>
<!-- end copyright info -->

<a href="#" class="scrollup">Scroll</a><!-- end scroll to top of the page-->

</div>

<!-- ######### JS FILES ######### -->

<!-- navigation -->
<script src="{% static 'js/navigation.js' %}" type="text/javascript"></script>

<!-- scroll up -->
<script src="{% static 'js/totop.js' %}" type="text/javascript"></script>

<!-- tabs -->
<script src="{% static 'js/tabs.js' %}" type="text/javascript"></script>

<!--Fancybox-->
<script src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
<script src="{% static 'js/jquery.fancybox-media.js' %}"></script>
<script src="{% static 'js/fancybox-init.js' %}"></script>


<div id="fb-root"></div>

<!-- socials -->
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>


{# TODO: facebook like box? #}
<script>
//facebook like box
(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/uk_UA/sdk.js#xfbml=1&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

{# TODO: custom sharethis #}
//sharethis
stLight.options({ publisher: "964f9f3a-e795-4c19-b5de-bd383ae7d57e", doNotHash: false, doNotCopy: false, hashAddressBar: false });
</script>


<!-- google -->
{# TODO: Google analytics #}
{# <script src="{% static 'js/analytics-init.js' %}"></script> #}

<!-- other scripts -->
<script src="{% static 'js/jquery.bxslider.min.js' %}"></script>
<script src="{% static 'js/slider-init.js' %}"></script>

templates/includes/footer.html
{% load i18n %}
{% load staticfiles %}

<footer>
  <div class="container">
    {% comment %}
    <hr>
    <div class="row">
      <div class="col-md-6 footer-left">
        <ul class="list-inline">
          <li>
            <a href="/{{ request.LANGUAGE_CODE }}/">{% trans 'Головна' %}</a>
          </li>
          <li>
            <a href="{% url 'about' %}" title="{% trans 'Про нас' %}">{% trans 'Про нас' %}</a>
          </li>
          {% for category in categories %}
          <li>
            <a href="{% url 'pages:category' category.slug %}">{{ category.title }}</a>
          </li>
          {% endfor %}
          <li>
            <a href="{% url 'news:news_list' %}">{% trans 'Новини' %}</a>
          </li>
          <li>
            <a href="{% url 'blog:post_list' %}" title="{% trans 'Блоги наших учасників' %}">{% trans 'Блоги' %}</a>
          </li>
        </ul>
        <p>
        </p>
      </div>
      <div class="col-md-6 footer-right">
      </div>
    </div>
    {% endcomment %}
    <hr>
    <div class="row">
      <div class="col-lg-12 footer-below">
        <p>© 2014 - {{ current_year }} {% trans 'Товариство дослідників України' %}</p>
        <p>{% trans 'Усі права захищено' %}</p>
      </div>
    </div>
  </div>
</footer>

templates/includes/ga.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55142914-1', 'auto');
    ga('send', 'pageview');

</script>

templates/includes/menu.html
{% load i18n %}
{% load staticfiles %}

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/{{ request.LANGUAGE_CODE }}/">TDUkr</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="{% trans 'Товариство' %}">{% trans 'Товариство' %} <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'about' %}" title="{% trans 'Про нас' %}">{% trans 'Про нас' %}</a></li>
            <li><a href="{% url 'join_as' %}" title="{% trans 'Анкета' %}">{% trans 'Анкета' %}</a></li>
          </ul>
        </li>

        {% for category in categories %}
          {% if category.get_children %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="{{ category.title }}">{{ category.title }} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                {% for sub_category in category.get_children %}
                <li>
                    <a href="{% url 'pages:category' sub_category.slug %}">{{ sub_category.title }}</a>
                </li>
                {% endfor %}
              </ul>
            </li>
          {% else %}
            <li>
              <a href="{% url 'pages:category' category.slug %}">{{ category.title }}</a>
            </li>
          {% endif %}
        {% endfor %}
{#        <li>#}
{#          <a href="#" title="{% trans 'Media' %}">{% trans 'Медіа' %}</a>#}
{#        </li>#}
{#        <li class="dropdown">#}
{#          <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="{% trans 'Блоги наших учасників' %}">{% trans 'Блоги' %} <b class="caret"></b></a>#}
{#          <ul class="dropdown-menu">#}
{#            {% for blogger in bloggers %}#}
{#            <li>#}
{#                <a href="{% url 'blog:blogger_name' blogger.username %}">{{ blogger.full_name }}</a>#}
{#            </li>#}
{#            {% endfor %}#}
{#          </ul>#}
{#        </li>#}
        <li>
          <a href="{% url 'news:news_list' %}">{% trans 'Новини' %}</a>
        </li>
        {# <li> #}
          {# <a href="{% url 'blog:post_list' %}" title="{% trans 'Блоги наших учасників' %}">{% trans 'Блоги' %}</a> #}
        {# </li> #}
      </ul>

      {# Langueges #}
      <ul class="nav navbar-nav navbar-right">
        <li>
	  <a hreflang="uk" href="/uk/{{ full_path_without_lang }}"><img src="{% static 'images/flags/uk.png' %}" title="Українська" alt="Українська" /></a>
        </li>
	{% comment %}
	<li>
	  <a hreflang="ru" href="/ru/{{ full_path_without_lang }}"><img src="{% static 'images/flags/ru_RU.png' %}" title="Русский" alt="Русский" /></a>
        </li>
	{% endcomment %}

        <li>
          <a hreflang="en" href="/en/{{ full_path_without_lang }}"><img src="{% static 'images/flags/en_US.png' %}" title="English" alt="English" /></a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

templates/includes/slider.html
{% load staticfiles %}
<!-- Use a container to wrap the slider, the purpose is to enable slider to always fit width of the wrapper while window resize -->
<div class="container">
    <!-- Jssor Slider Begin -->
    <!-- To move inline styles to css file/block, please specify a class name for each element. -->
    <!-- ================================================== -->
    <div id="slider1_container" style="display: none; position: relative; margin: 0 auto; width: 1140px; height: 442px; overflow: hidden;">

        <!-- Loading Screen -->
        <div u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;

            background-color: #000; top: 0px; left: 0px;width: 100%; height:100%;">
            </div>
            <div style="position: absolute; display: block; background: url(../img/loading.gif) no-repeat center center;

            top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
        </div>

        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1140px; height: 350px;
        overflow: hidden;">
            <div>
                <img u="image" src2="{% static 'panorams/kiyv.jpg' %}" />
            </div>
            <div>
                <img u="image" src2="{% static 'panorams/kyiv2.jpg' %}" />
            </div>
            <div>
                <img u="image" src2="{% static 'panorams/chernigiv.jpg' %}" />
            </div>
            <div>
                <img u="image" src2="{% static 'panorams/lake.jpg' %}" />
            </div>
            <div>
                <img u="image" src2="{% static 'panorams/lviv.jpg' %}" />
            </div>
            <div>
                <img u="image" src2="{% static 'panorams/river.jpg' %}" />
            </div>
            <div>
                <img u="image" src2="{% static 'panorams/mountains.jpg' %}" />
            </div>
        </div>

        <!--#region Bullet Navigator Skin Begin -->
        <!-- Help: http://www.jssor.com/development/slider-with-bullet-navigator-jquery.html -->
        <style>
            /* jssor slider bullet navigator skin 05 css */
            /*
            .jssorb05 div           (normal)
            .jssorb05 div:hover     (normal mouseover)
            .jssorb05 .av           (active)
            .jssorb05 .av:hover     (active mouseover)
            .jssorb05 .dn           (mousedown)
            */
            .jssorb05 {
                position: absolute;
            }
            .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
                position: absolute;
                /* size of bullet elment */
                width: 16px;
                height: 16px;
                background: url(../img/b05.png) no-repeat;
                overflow: hidden;
                cursor: pointer;
            }
            .jssorb05 div { background-position: -7px -7px; }
            .jssorb05 div:hover, .jssorb05 .av:hover { background-position: -37px -7px; }
            .jssorb05 .av { background-position: -67px -7px; }
            .jssorb05 .dn, .jssorb05 .dn:hover { background-position: -97px -7px; }
        </style>
        <!-- bullet navigator container -->
        <div u="navigator" class="jssorb05" style="bottom: 16px; right: 6px;">
            <!-- bullet navigator item prototype -->
            <div u="prototype"></div>
        </div>
        <!--#endregion Bullet Navigator Skin End -->

        <!--#region Arrow Navigator Skin Begin -->
        <!-- Help: http://www.jssor.com/development/slider-with-arrow-navigator-jquery.html -->
        <style>
            /* jssor slider arrow navigator skin 11 css */
            /*
            .jssora11l                  (normal)
            .jssora11r                  (normal)
            .jssora11l:hover            (normal mouseover)
            .jssora11r:hover            (normal mouseover)
            .jssora11l.jssora11ldn      (mousedown)
            .jssora11r.jssora11rdn      (mousedown)
            */
            .jssora11l, .jssora11r {
                display: block;
                position: absolute;
                /* size of arrow element */
                width: 37px;
                height: 37px;
                cursor: pointer;
                background: url(../img/a11.png) no-repeat;
                overflow: hidden;
            }
            .jssora11l { background-position: -11px -41px; }
            .jssora11r { background-position: -71px -41px; }
            .jssora11l:hover { background-position: -131px -41px; }
            .jssora11r:hover { background-position: -191px -41px; }
            .jssora11l.jssora11ldn { background-position: -251px -41px; }
            .jssora11r.jssora11rdn { background-position: -311px -41px; }
        </style>
        <!-- Arrow Left -->
        <span u="arrowleft" class="jssora11l" style="top: 123px; left: 8px;">
        </span>
        <!-- Arrow Right -->
        <span u="arrowright" class="jssora11r" style="top: 123px; right: 8px;">
        </span>
        <!--#endregion Arrow Navigator Skin End -->
        <a style="display: none" href="http://www.jssor.com">Bootstrap Slider</a>
    </div>
    <!-- Jssor Slider End -->
</div>

templates/includes/ym.html
<!-- Yandex.Metrika counter --><script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter26500413 = new Ya.Metrika({ id:26500413, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/26500413" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->