blog/urls.py
# coding: utf-8

from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse, resolve
from views import post_list, post_item, blogger_page


urlpatterns = patterns('',
    url(r'^$', post_list, name='post_list'),
    url(r'post/(?P<slug>[-\w]*)/$', post_item, name='post_item'),
    url(r'blogger/(?P<username>[\w]*)/$', blogger_page, name='blogger_name'),
)

news/urls.py
# coding: utf-8

from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse, resolve

from views import news_list, news_article


urlpatterns = patterns('',
    url(r'^$', news_list, name='news_list'),
    url(r'(?P<slug>[-\w]*)/$', news_article, name='news_article'),
)

tdukr/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns('',
    url(r'^$', 'core.views.home', name='home'),
    url(r'^about/$', 'core.views.about', name='about'),
    url(r'^about/join-as/$', 'core.views.join_as', name='join_as'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^pages/', include('pages.urls', namespace='pages')),
    url(r'^news/', include('news.urls', namespace='news')),


)

urlpatterns += patterns('',
    url(r'^decent/', 'decent.views.index', name='decent_index'),
)


if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

blog/models.py
# coding: utf-8

import datetime

from django.db import models
from django.db.models import signals
from django.conf import settings
from django.utils.translation import ugettext as _

from core.models.transmeta import TransMeta
from core.models import TimeStampedModel, MetaDataModel, PublishedModel
from core.manager import PublishableManager


class Post(MetaDataModel, TimeStampedModel, PublishedModel):
    __metaclass__ = TransMeta

    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               verbose_name=_('Author'), blank=True, null=True)
    title = models.CharField(_(u'Title'), max_length=255)
    image = models.ImageField(_(u'Image'), upload_to='upload/blogpost', blank=True, null=True)
    body = models.TextField(_(u'Content'), blank=True, null=True)
    short_body = models.TextField(_(u'Short content'), blank=True, null=True)
    slug = models.SlugField(_(u'Slug'), blank=True, null=True, unique=True)

    objects = PublishableManager()

    class Meta:
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ('-publish_date', 'created', 'id')
        translate = ('title', 'body', 'short_body')

    def __unicode__(self):
        return u'{author}: {title}'.format(author=self.author, title=self.title)


def update_post_publish_status(sender, instance, **kwargs):
    if instance.publish_status == Post.CONTENT_STATUS_PUBLISHED and not instance.publish_date:
        now = datetime.datetime.now()
        instance.publish_date = now

signals.pre_save.connect(update_post_publish_status, sender=Post)

core/models/about.py
# coding: utf-8

from django.db import models
from django.utils.translation import ugettext as _

from transmeta import TransMeta


class About(models.Model):
    __metaclass__ = TransMeta

    content = models.TextField(_(u'About text'))

    class Meta:
        verbose_name = _(u'About')
        verbose_name_plural = _(u'About')
        translate = ('content',)

    def __unicode__(self):
        return u'About'

core/models/base.py
# coding: utf-8

from django.db import models
from django.utils.translation import ugettext as _

from core.models.transmeta import TransMeta

__all__ = (
    'MetaDataModel',
    'TimeStampedModel',
    'PublishedModel'
)


class MetaDataModel(models.Model):
    """
    Abstract model that provides meta data for content.
    """
    __metaclass__ = TransMeta

    meta_title = models.CharField(_(u'Meta title'), max_length=500, blank=True)
    meta_description = models.TextField(_('Meta description'), blank=True)
    meta_keywords = models.CharField(verbose_name=_('Meta keywords'), max_length=500, blank=True)

    class Meta:
        abstract = True
        translate = ('meta_title', 'meta_description', 'meta_keywords')

    def __unicode__(self):
        return self.meta_title


class TimeStampedModel(models.Model):
    """
    Provides created and updated timestamps on models.
    """
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __unicode__(self):
        return super(TimeStampedModel, self).__unicode__()


class PublishedModel(models.Model):
    CONTENT_STATUS_DRAFT = 1
    CONTENT_STATUS_PUBLISHED = 2
    CONTENT_STATUS_CHOICES = (
        (CONTENT_STATUS_DRAFT, _('Draft')),
        (CONTENT_STATUS_PUBLISHED, _('Published')),
    )

    publish_status = models.IntegerField(_('Status'),
        choices=CONTENT_STATUS_CHOICES, default=CONTENT_STATUS_DRAFT,
        help_text=_('With Draft chosen, will only be shown in admin interface.'))
    publish_date = models.DateTimeField(_('Published from'),
        help_text=_("With Published chosen, won't be shown until this time"),
        blank=True, null=True)
    expiry_date = models.DateTimeField(_('Expires on'),
        help_text=_("With Published chosen, won't be shown after this time"),
        blank=True, null=True)

    class Meta:
        abstract = True

    def __unicode__(self):
        return super(PublishedModel, self).__unicode__()

    @property
    def is_published(self):
        return self.status == self.CONTENT_STATUS_PUBLISHED

templates/about.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content %}

<header class="sb-page-header">
    <div class="container">
      <h1>{% trans 'Про нас' %}</h1>
    </div>
</header>

<!-- Page Content -->
    {# Breadcrumbs #}
<div class="container">
	<ol class="breadcrumb">
		<li><a href="/{{ request.LANGUAGE_CODE }}/">{% trans 'Головна' %}</a></li>
		<li class="active">{% trans 'Про нас' %}</li>
	</ol>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
          {{ about.content|safe }}
{#            <h2><i class="fa fa-support"></i> Help Requests</h2>#}
{#            <p>If you need help with one of our templates, or if you are experiencing a bug, please visit <a href="/help">our help page</a>. If you still can't find an answer, please email us at:</p>#}
{#            <p><strong><a href="mailto:help@startbootstrap.com">help@startbootstrap.com</a></strong></p>#}
{#            <h2><i class="fa fa-code"></i> Hire Us!</h2>#}
{#            <p>Do you want a custom Bootstrap theme? Do you like one of our templates, but want some additional features added? If so, you can hire the Start Bootstrap team to get your custom project done! We build HTML/CSS Bootstrap themes on a per project basis. We can work from design concepts, examples of other designs you like, or from PSD's! If you're interested in our custom design services, <a href="/bootstrap-design-services/">click here for more information</a>, or email us at:</p>#}
{#            <p><strong><a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a></strong></p>#}

        </div>
    </div>

</div>

  {% comment %}
  <!-- Footer -->
  <div class="cta-mail">
    <div class="container text-center">
        <h2>Want more Bootstrap themes &amp; templates?</h2>
        <h4>Subscribe to our mailing list to receive an update when new items arrive!</h4>
        <div id="mc_embed_signup">
            <form role="form" action="http://startbootstrap.us3.list-manage1.com/subscribe/post?u=531af730d8629808bd96cf489&amp;id=afb284632f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" novalidate>
                <div class="input-group input-group-lg">
                    <input type="email" name="EMAIL" class="form-control" id="mce-EMAIL" placeholder="Email address...">
                    <span class="input-group-btn">
                        <button type="submit" name="subscribe" id="mc-embedded-subscribe" class="btn btn-default">Subscribe!</button>
                    </span>
                </div>
                <div id="mce-responses">
                    <div class="response" id="mce-error-response" style="display:none"></div>
                    <div class="response" id="mce-success-response" style="display:none"></div>
                </div>
            </form>
        </div>
        <!-- End MailChimp Signup Form -->
    </div>
  </div>
  {% endcomment %}

{% endblock %}

templates/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- TODO -> -->
    <meta name="description" content="TDUkr">
    <meta name="author" content="sonych">

    <title>{% trans 'Society researcher of Ukraine' %} | {% block title %}{% endblock %}</title>

    <!-- Fav Icon and Apple Touch Icons -->
    <link rel="icon" href="{% static 'assets/img/ico/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'assets/img/ico/touch-icon-iphone.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/ico/touch-icon-ipad.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'assets/img/ico/touch-icon-iphone-retina.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'assets/img/ico/touch-icon-ipad-retina.png' %}">

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400italic,700italic,400,700" rel="stylesheet" type="text/css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Start Bootstrap Custom CSS -->
    <link href="{% static 'assets/css/startbootstrap.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static 'assets/css/tdukr.css' %}" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Webmaster Tools Site Verification -->
    <!-- TODO: change -->
    <!-- <meta name="google-site-verification" content="hq9-_keIZdTZt7arZ91T-gSqn8ANii362mlcn0zCgno"> -->

  {% for lang_code, lang_name in LANGUAGES %}
    <link rel="alternate" href="http://{{ HOSTNAME }}/{{ lang_code }}/" hreflang="{{ lang_code }}" />
  {% endfor %}
 
  {% include 'includes/ga.html' %}
  {% include 'includes/ym.html' %}

</head>

<body>

{% block body_head %}{% endblock %}

{% include 'includes/menu.html' %}

{% block content %}

{% endblock %}

{% include 'includes/footer.html' %}

<!-- JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="{% static 'assets/js/docs.js' %}"></script>
<script src="{% static 'assets/js/startbootstrap.js' %}"></script>

{% block extra_js %}
{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load i18n %}

{% block head_extra_js %}



{% endblock %}

{% block content %}

  <header class="sb-page-header">
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          {% if request.LANGUAGE_CODE == 'uk' %}
            <img src="{% static 'assets/img/logo/logo_uk.png' %}" class="logo">
          {% elif request.LANGUAGE_CODE == 'en' %}
            <img src="{% static 'assets/img/logo/logo_en.png' %}" class="logo">
{#          {% elif request.LANGUAGE_CODE == 'ru' %}#}
{#            <img src="{% static 'assets/img/logo/logo_ru.png' %}" class="logo">#}
          {% endif %}
        </div>
        <div class="col-md-8 home-header">
          <p>{% trans 'Товариство' %}</p>
          <p>{% trans 'Дослідників' %}</p>
          <p>{% trans 'України' %}</p>
        </div>
        <div class="col-md-2" style="margin-top: 95px; text-align: right;">
          <a href="https://www.facebook.com/tdukr" target="_blank"><img src="{% static 'tdukr/soc_icons/fb.png' %}" style="margin-right: 10px;"></a>
          <a href="https://www.instagram.com/ukrainian_researchers_society/" target="_blank"><img src="{% static 'tdukr/soc_icons/instagram.png' %}" style="margin-right: 10px;"></a>
          <a href="mailto:ngo.tdu@gmail.com" target="_blank"><img src="{% static 'tdukr/soc_icons/email.png' %}"></a>
          
        </div>
      </div>
    </div>
  </header>
  
  {% include 'includes/slider.html' %}

  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">{% trans 'News' %}</h3>
          </div>
          <div class="panel-body">
            <ul class="list-group">
              {% for article in articles %}
              <li class="list-group-item" style="border: 0;">
                <span class="badge">{{ article.publish_date|date:'d.m.Y' }}</span>
                <a href="{% url 'news:news_article' article.slug %}">{{ article.title }}</a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>

      <div class="col-md-5">
        <h3 style="font-family: Impact; color: #0A5CC0; text-align: center; padding-top: 20px;">ТОВАРИСТВО ДОСЛІДНИКІВ УКРАЇНИ</h3>
        <p style="text-align: center;">об’єднання молодих вчених, яке здійснює заходи по сприянню організації розвитку, підвищенню ефективності досліджень культурного, історичного, соціально-економічного розвитку регіонів України, оптимізації взаємодії суспільства і природи.</p>

        {% comment %}
        <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
          <ul id="myTab" class="nav nav-tabs" role="tablist">
            {% for blogger in bloggers %}
            <li role="presentation" {% if forloop.first %}class="active"{% endif %}>
              <a href="#{{ blogger.username }}" id="{{ blogger.username }}-tab" role="tab" data-toggle="tab" aria-controls="{{ blogger.username }}" aria-expanded="true">{{ blogger.full_name }}</a>
            </li>
            {% endfor %}
          </ul>
          <div id="myTabContent" class="tab-content">
            {% for blogger in bloggers %}
            <div role="tabpanel" class="tab-pane fade{% if forloop.first %} active in{% endif %}" id="{{ blogger.username }}" aria-labelledby="{{ blogger.username }}-tab">
              {% for post in blogger.post_set.published %}
                <div class="post text">
                  <h5><a href="{% url 'blog:post_item' post.slug %}">{{ post.title }}</a></h5>
                  {{ post.short_body|safe }}
                </div>
              {% endfor %}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endcomment %}
      </div>
      <div class="col-md-4">
        <a href="/uk/pages/category/decentralizaciya/"><img src="{% static 'tdukr/d.jpg' %}" style="padding-bottom: 15px;"></a>
        <a href="/uk/pages/category/pamyat-miscya-pamyat-narodu/"><img src="{% static 'tdukr/pp.jpg' %}" style="padding-bottom: 15px;"></a>
        <a href="/uk/pages/page/pro-proekt-de-pochinayetsya-ukrayina/"><img src="{% static 'tdukr/dpg.jpg' %}" style="padding-bottom: 15px;"></a>
        <a href="/uk/pages/category/tripar/"><img src="{% static 'tdukr/sc.png' %}" style="padding-bottom: 15px;"></a>
      </div>
    </div>

  {% comment %}
    <!-- Partners -->
    <div class="row">


      <!-- Jssor Slider Begin -->
    <!-- To move inline styles to css file/block, please specify a class name for each element. -->
    <div id="slider1_container_2" style="position: relative; top: 0px; left: 0px; width: 980px; height: 100px; overflow: hidden; ">

        <!-- Loading Screen -->
        <div u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
                background-color: #000; top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
            <div style="position: absolute; display: block; background: url(../img/loading.gif) no-repeat center center;
                top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
        </div>

        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 980px; height: 100px; overflow: hidden;">
          {% for partner in partners %}
            <div><img u="image" width="300" height="300" alt="{{ partner.title }}" src="{{ partner.image.url }}" /></div>
          {% endfor %}
{#            <div><img u="image" alt="amazon" src="{% static 'imggg/logo/amazon.jpg' %}" /></div>#}
{#            <div><img u="image" alt="android" src="{% static 'imggg/logo/android.jpg' %}" /></div>#}
{#            <div><img u="image" alt="bitly" src="{% static 'imggg/logo/bitly.jpg' %}" /></div>#}
{#            <div><img u="image" alt="blogger" src="{% static 'imggg/logo/blogger.jpg' %}" /></div>#}
{#            <div><img u="image" alt="dnn" src="{% static 'imggg/logo/dnn.jpg' %}" /></div>#}
{#            <div><img u="image" alt="drupal" src="{% static 'imggg/logo/drupal.jpg' %}" /></div>#}
{#            <div><img u="image" alt="ebay" src="{% static 'imggg/logo/ebay.jpg' %}" /></div>#}
{#            <div><img u="image" alt="facebook" src="imggg/logo/facebook.jpg" /></div>#}
{#            <div><img u="image" alt="google" src="{% static 'imggg/logo/google.jpg' %}" /></div>#}
{#            <div><img u="image" alt="ibm" src="{% static 'imggg/logo/ibm.jpg' %}" /></div>#}
{#            <div><img u="image" alt="ios" src="{% static 'imggg/logo/ios.jpg' %}" /></div>#}
{#            <div><img u="image" alt="joomla" src="{% static 'imggg/logo/joomla.jpg' %}" /></div>#}
{#            <div><img u="image" alt="linkedin" src="{% static 'imggg/logo/linkedin.jpg' %}" /></div>#}
{#            <div><img u="image" alt="mac" src="{% static 'imggg/logo/mac.jpg' %}" /></div>#}
{#            <div><img u="image" alt="magento" src="{% static 'imggg/logo/magento.jpg' %}" /></div>#}
{#            <div><img u="image" alt="pinterest" src="{% static 'imggg/logo/pinterest.jpg' %}" /></div>#}
{#            <div><img u="image" alt="samsung" src="{% static 'imggg/logo/samsung.jpg' %}" /></div>#}
{#            <div><img u="image" alt="twitter" src="{% static 'imggg/logo/twitter.jpg' %}" /></div>#}
{#            <div><img u="image" alt="windows" src="{% static 'imggg/logo/windows.jpg' %}" /></div>#}
{#            <div><img u="image" alt="wordpress" src="{% static 'imggg/logo/wordpress.jpg' %}" /></div>#}
{#            <div><img u="image" alt="youtube" src="{% static 'imggg/logo/youtube.jpg' %}" /></div>#}
        </div>
        <a style="display: none" href="http://www.jssor.com">Bootstrap Slider</a>
    </div>
    <!-- Jssor Slider End -->

    </div>
{% endcomment %}


    <div class="row" style="padding-top: 50px;">
	    {# <div class="col-lg-12"> #}	     
	      {#      <h3 style="text-align: center;">{% trans 'Партнери' %}</h3> #}
	    {# </div> #}
    </div>
    <div class="row">
      <hr>
{% comment %}
      <div class="col-lg-4" style="text-align: center">
        <a href="http://www.nationalgeographic.com/" target="_blank">
        <img src="{% static 'tdukr/sponsors/ng.png' %}">
        </a>
      </div>
      <div class="col-lg-4" style="text-align: center">
        <a href="http://www.geograf.com.ua/" target="_blank">
        <img src="{% static 'tdukr/sponsors/geograf.png' %}">
        </a>
      </div>
      <div class="col-lg-4" style="text-align: center">
        <a href="http://www.memory.gov.ua/" target="_blank">
        <img src="{% static 'tdukr/sponsors/uinp.png' %}">
        </a>
      </div>
    </div>
{% endcomment %}
  </div>

  {% block extra_js %}
    {{ block.super }}
    <script src="{% static 'js/jssor.slider.mini.js' %}"></script>
    <script>
        jQuery(document).ready(function ($) {
            var options = {
              $AutoPlay: true,
              $AutoPlayInterval: 1900
            };

            $("#slider1_container").css("display", "block");
            var jssor_slider1 = new $JssorSlider$("slider1_container", options);

        });
    </script>

{% comment %}
    <script>
        jQuery(document).ready(function ($) {
            var options = {
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlaySteps: 1,                                  //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1
                $AutoPlayInterval: 0,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $PauseOnHover: 4,                               //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

                $ArrowKeyNavigation: true,   			            //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
                $SlideEasing: $JssorEasing$.$EaseLinear,          //[Optional] Specifies easing for right to left animation, default value is $JssorEasing$.$EaseOutQuad
                $SlideDuration: 1600,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $MinDragOffsetToSlide: 20,                          //[Optional] Minimum drag offset to trigger slide , default value is 20
                $SlideWidth: 300,                                   //[Optional] Width of every slide in pixels, default value is width of 'slides' container
                $SlideHeight: 200,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
                $SlideSpacing: 20, 					                //[Optional] Space between each slide in pixels, default value is 0
                $DisplayPieces: 7,                                  //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
                $ParkingPosition: 0,                              //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
                $UISearchMode: 1,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
                $PlayOrientation: 1,                                //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
                $DragOrientation: 1                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
            };

            var jssor_slider1_2 = new $JssorSlider$("slider1_container_2", options);

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var bodyWidth = document.body.clientWidth;
                if (bodyWidth) {
                  jssor_slider1_2.$ScaleWidth(Math.min(bodyWidth, 1140));
                  jssor_slider1_2.$ScaleHeight(200);
                }
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>
{% endcomment %}

  {% endblock %}

{% endblock %}

templates/join_as.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<header class="sb-page-header">
    <div class="container">
        <h1>{% trans 'Анкета учасника' %}</h1>
        <p>
          {% blocktrans %}
          Заповни анкету щоб стати учасником товариства
          {% endblocktrans %}
        </p>
    </div>
</header>

<!-- Page Content -->
    {# Breadcrumbs #}
<div class="container">
	<ol class="breadcrumb">
		<li><a href="/{{ request.LANGUAGE_CODE }}/">{% trans 'Головна' %}</a></li>
		<li><a href="{% url 'about' %}">{% trans 'Про нас' %}</a></li>
    <li class="active">{% trans 'Анкета учасника' %}</li>
	</ol>
</div>

<div class="container">

   {% if form %}

   <form class="form-horizontal" role="form" method="POST">
     {% for field in form %}
      <div class="form-group">
          <label for="firstname" class="col-sm-2 control-label">{{ field.label }} {% if field.help_text %}({{ field.help_text }}){% endif %}</label>
          <div class="col-sm-10">
            {{ field }}
            <span style="color: red;">{{ field.errors }}</span>
          </div>
       </div>
     {% endfor %}



     <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
             <button type="submit" class="btn btn-default">{% trans 'Подати заявку' %}</button>
          </div>
       </div>
   </form>

  {% else %}

     <h3>{% trans 'Дякую за заявку!' %}</h3>

  {% endif %}

</div>

{% endblock %}